# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


tot = 0
a = 0
b = 1
h = 1
limit = 4000000

while h <= limit:
    if h % 2 == 0:
        tot += h
    a = b
    b = h
    h = a + b

print(tot)