apiVersion: v1
data:
  ca.crt: ***==
  namespace: dmF1bHQ=
  token: ***==
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: vault-k8s-auth
  name: vault-k8s-auth
  namespace: vault
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-k8s-auth
  namespace: vault
secrets:
  - name: vault-k8s-auth  
---
